### PR TITLE
scene to use `main` field

### PR DESCRIPTION
**Pull request by ZhouHansen**
use `main` field when there is no `style` field and the `main` field
points to css file.

### CODE REVIEW

**Comment by s3ththompson** [comment]
I just turned on Travis CI for this repo. Can you add a `.travis.yml` and push again?

**Comment by ZhouHansen** [comment]
Added~

**Comment by ZhouHansen** [comment]
How about release a new version?

**Comment by s3ththompson** [comment]
Perhaps ping Yosh on choo IRC?

**Comment by yoshuawuyts** [comment]
`v1.1.0`. Sorry for the delay all! If you link your npm profiles, I'll add you both to npm so this never happens again. Thanks!

**Comment by ZhouHansen** [comment]
Oh, thanks! this is my npm profile: https://www.npmjs.com/~zhouhancheng

**Comment by s3ththompson** [comment]
Sweet! https://www.npmjs.com/~s3ththompson

**Pull request merged**
